version: '3.1'

services:
  python:
    build: .
    restart: always
    container_name: bot_rest
    command: python main.py
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
    environment:
      - TZ=Europe/Moscow

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data/
    container_name: db

  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}
    container_name: redis

volumes:
  postgres: null
